<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Savostytskyi" name="Default test" tests="7" failures="1" timestamp="17 May 2015 20:46:36 GMT" time="3.703" errors="0">
  <testcase name="buildTest" time="0.16" classname="epam.com.game.GameTest">
    <failure type="java.lang.IllegalStateException" message="missing behavior definition for the preceding method call:
CitiesDBParser.cityesDocumentParser()
Usage is: expect(a.foo()).andXXX()">
      <![CDATA[java.lang.IllegalStateException: missing behavior definition for the preceding method call:
CitiesDBParser.cityesDocumentParser()
Usage is: expect(a.foo()).andXXX()
	at org.easymock.internal.MocksControl.replay(MocksControl.java:231)
	at org.easymock.EasyMock.replay(EasyMock.java:2032)
	at epam.com.game.GameTest.buildTest(GameTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- buildTest -->
  <testcase name="prepareGameTest" time="1.801" classname="epam.com.game.GameTest"/>
  <testcase name="prepareGameTest" time="1.68" classname="epam.com.game.GameTest"/>
  <testcase name="prepareGameTestF" time="0.0" classname="epam.com.game.GameTest"/>
  <testcase name="prepareGameTestF" time="0.0" classname="epam.com.game.GameTest"/>
  <testcase name="prepareGameTestF" time="0.0" classname="epam.com.game.GameTest"/>
  <testcase name="prepareGameTestF" time="0.0" classname="epam.com.game.GameTest"/>
</testsuite> <!-- Default test -->
